version: '3.5' #Specifies the docker rcompose version

#Defining the services/containers to be executed
services:
    angular-service: ##name of the first service
        container_name: dpa_client
        build: ./ #specify the directory of the Dockerfile
        volumes: #Volume binding
        - './:/usr/src/app'
        ports:
            - "4202:4200" #Specify port forewarding
        command: >
            bash -c "npm start"

    docker-nginx:
        container_name: dpa_nginx
        build: ./
        ports:
            - "81:81"
        command: ["nginx", "-g", "daemon off;"]
        links:
            - angular-service


